# ============================================================================
# Dependabot Configuration for Brain2Gain
# Automated dependency updates for security and maintenance
# ============================================================================

version: 2

updates:
  # ============================================================================
  # Python Dependencies (Backend)
  # ============================================================================
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "brain2gain-team"
    assignees:
      - "brain2gain-team"
    commit-message:
      prefix: "deps(backend)"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
      - "python"
    # Group minor and patch updates
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Security updates get separate PRs immediately
    security-updates:
      enabled: true
    # Ignore specific packages if needed
    ignore:
      - dependency-name: "setuptools"
        versions: [">=70.0.0"]
    # Version update strategies
    versioning-strategy: "increase"

  # ============================================================================
  # Node.js Dependencies (Frontend)
  # ============================================================================
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "brain2gain-team"
    assignees:
      - "brain2gain-team"
    commit-message:
      prefix: "deps(frontend)"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
      - "nodejs"
    # Group development dependencies separately
    groups:
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "@testing-library/*"
          - "eslint*"
          - "prettier*"
          - "vitest*"
          - "playwright*"
        update-types:
          - "minor"
          - "patch"
      
      development-dependencies:
        patterns:
          - "@types/*"
          - "@testing-library/*"
          - "eslint*"
          - "prettier*"
          - "vitest*"
          - "playwright*"
        update-types:
          - "minor"
          - "patch"
    # Security updates
    security-updates:
      enabled: true
    # Version update strategies
    versioning-strategy: "increase"

  # ============================================================================
  # Docker Dependencies
  # ============================================================================
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "brain2gain-team"
    assignees:
      - "brain2gain-team"
    commit-message:
      prefix: "deps(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "backend"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "brain2gain-team"
    assignees:
      - "brain2gain-team"
    commit-message:
      prefix: "deps(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "frontend"

  # ============================================================================
  # GitHub Actions Dependencies
  # ============================================================================
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "brain2gain-team"
    assignees:
      - "brain2gain-team"
    commit-message:
      prefix: "deps(actions)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci-cd"
    # Group all GitHub Actions updates
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"