services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_DB=brain2gain_prod
      - POSTGRES_USER=brain2gain_owner
      - POSTGRES_PASSWORD=ClaveDura!2025
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U brain2gain_owner -d brain2gain_prod"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass RedisPass2025
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build: ./backend
    env_file: .env
    volumes:
      - ./backend/app:/app/app
      - ./backend/alembic.ini:/app/alembic.ini
      - ./backend/entrypoint.sh:/app/entrypoint.sh
      - ./backend/migrations:/app/migrations
      - ./backend/pyproject.toml:/app/pyproject.toml
      - ./backend/poetry.lock:/app/poetry.lock
      - ./dashboard:/app/dashboard
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: >
      bash -c "cd /app &&
               sleep 10 &&
               alembic -c alembic.ini upgrade head &&
               uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - PYTHONPATH=/app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=RedisPass2025

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src     # hot-reload React
      - ./frontend/public:/app/public
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:8000

volumes:
  postgres_data:
  redis_data:

