services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_DB=brain2gain_prod
      - POSTGRES_USER=brain2gain_owner
      - POSTGRES_PASSWORD=ClaveDura!2025
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file: .env
    volumes:
      - ./backend/app:/app/app
      - ./backend/alembic.ini:/app/alembic.ini
      - ./backend/entrypoint.sh:/app/entrypoint.sh
      - ./backend/migrations:/app/migrations
      - ./backend/pyproject.toml:/app/pyproject.toml
      - ./backend/poetry.lock:/app/poetry.lock
      - ./dashboard:/app/dashboard
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    command: >
      bash -c "cd /app &&
               sleep 10 &&
               alembic -c alembic.ini upgrade head &&
               uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - PYTHONPATH=/app

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src     # hot-reload React
      - ./frontend/public:/app/public
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:8000

volumes:
  postgres_data:

