# ═══════════════════════════════════════════════════════════════════
# Base Infrastructure Services - Shared Configuration
# ═══════════════════════════════════════════════════════════════════

# Common configurations
x-common-variables: &common-variables
  TZ: America/Mexico_City
  PYTHONUNBUFFERED: "1"
  PYTHONDONTWRITEBYTECODE: "1"

x-postgres-healthcheck: &postgres-healthcheck
  test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-brain2gain_user} -d ${POSTGRES_DB:-brain2gain}"]
  interval: 10s
  timeout: 5s
  retries: 5
  start_period: 30s

x-redis-healthcheck: &redis-healthcheck
  test: ["CMD", "redis-cli", "--no-auth-warning", "ping"]
  interval: 10s
  timeout: 5s
  retries: 3
  start_period: 20s

services:
  # ═══════════════════════════════════════════════════════════════════
  # DATABASE SERVICES
  # ═══════════════════════════════════════════════════════════════════

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      <<: *common-variables
      POSTGRES_DB: ${POSTGRES_DB:-brain2gain}
      POSTGRES_USER: ${POSTGRES_USER:-brain2gain_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Variable not set}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql:ro
      - ../database/backups:/backups:rw
    healthcheck: *postgres-healthcheck
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    environment:
      <<: *common-variables
    command: |
      redis-server 
      --appendonly yes 
      --requirepass ${REDIS_PASSWORD?Variable not set}
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    healthcheck: *redis-healthcheck
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'

  # ═══════════════════════════════════════════════════════════════════
  # ADMINISTRATION TOOLS
  # ═══════════════════════════════════════════════════════════════════

  adminer:
    image: adminer:4.8.1
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      <<: *common-variables
      ADMINER_DESIGN: pepa-linha-dark
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DEFAULT_DB: ${POSTGRES_DB:-brain2gain}
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'
    profiles:
      - tools

  mailcatcher:
    image: schickling/mailcatcher
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'
    profiles:
      - tools

# ═══════════════════════════════════════════════════════════════════
# SHARED RESOURCES
# ═══════════════════════════════════════════════════════════════════

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  brain2gain-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1