# Grafana Datasources Configuration

apiVersion: 1

datasources:
  # Prometheus datasource
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.48.0
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m

  # Elasticsearch datasource for logs
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    orgId: 1
    url: http://elasticsearch:9200
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    jsonData:
      index: 'brain2gain-logs-*'
      timeField: '@timestamp'
      esVersion: '8.11.0'
      logMessageField: 'message'
      logLevelField: 'level'
      maxConcurrentShardRequests: 5