"""stock one-to-one fix

Revision ID: 9da22a6a6941
Revises: d3a5d3d97a7d
Create Date: 2025-05-05 23:32:25.062734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlmodel.sql.sqltypes import AutoString

# revision identifiers, used by Alembic.
revision: str = '9da22a6a6941'
down_revision: Union[str, None] = 'd3a5d3d97a7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'DISCONTINUED', name='productstatus'),
               type_= AutoString(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'status',
               existing_type= AutoString(),
               type_=postgresql.ENUM('ACTIVE', 'DISCONTINUED', name='productstatus'),
               nullable=True)
    # ### end Alembic commands ###
