"""stock one-to-one fix

Revision ID: d3a5d3d97a7d
Revises: 32a4f7336f57
Create Date: 2025-05-05 23:26:35.667851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3a5d3d97a7d'
down_revision: Union[str, None] = '32a4f7336f57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('stock_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'stock_id')
    # ### end Alembic commands ###
