# Filebeat Configuration for Brain2Gain

# Filebeat inputs
filebeat.inputs:
  # Docker container logs
  - type: container
    paths:
      - '/var/lib/docker/containers/*/*.log'
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true
    
  # Application logs
  - type: log
    enabled: true
    paths:
      - '/opt/brain2gain/logs/backend/*.log'
    fields:
      service: backend
      application: brain2gain-backend
    fields_under_root: true
    multiline.pattern: '^\d{4}-\d{2}-\d{2}'
    multiline.negate: true
    multiline.match: after
    
  - type: log
    enabled: true
    paths:
      - '/opt/brain2gain/logs/frontend/*.log'
    fields:
      service: frontend
      application: brain2gain-frontend
    fields_under_root: true
    
  # System logs
  - type: log
    enabled: true
    paths:
      - '/var/log/syslog'
      - '/var/log/auth.log'
      - '/var/log/kern.log'
    fields:
      service: system
    fields_under_root: true

# Processors
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
  - timestamp:
      field: json.time
      layouts:
        - '2006-01-02T15:04:05.000Z'
        - '2006-01-02T15:04:05Z'
      test:
        - '2019-06-22T16:33:51.000Z'

# Global processors
processors:
  - add_tags:
      tags: [brain2gain, production]
      target: ""

# Output configuration
output.logstash:
  hosts: ["logstash:5044"]
  compression_level: 3
  bulk_max_size: 2048
  worker: 1

# Alternative: Direct Elasticsearch output (disable logstash output if using this)
# output.elasticsearch:
#   hosts: ["elasticsearch:9200"]
#   index: "brain2gain-logs-%{+yyyy.MM.dd}"
#   template.settings:
#     index.number_of_shards: 1
#     index.number_of_replicas: 0

# Logging configuration
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

# Monitoring
monitoring.enabled: true

# Enable modules
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# Autodiscover
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      hints.default_config:
        type: container
        paths:
          - /var/lib/docker/containers/${data.docker.container.id}/*.log